/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mini.zoo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
/**
 *
 * @author mierd
 */
public class MiniZooMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MiniZooMainMenu
     */
    public MiniZooMainMenu() {
        initComponents();
//        Image image = new ImageIcon(getClass().getResource("/img/logoJXIII.png")).getImage();
//
//        // Establecer el icono
//        setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAction = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Que animal eres?");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(99, 34, 0));
        jLabel1.setText("¿Que animal eres?");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 30, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Este programa te dira el animal que serias si volvieras a nacer.");

        btnAction.setBackground(new java.awt.Color(23, 142, 24));
        btnAction.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAction.setForeground(java.awt.Color.white);
        btnAction.setText("Quiero saber!");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        btnAbout.setBackground(java.awt.Color.lightGray);
        btnAbout.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        btnAbout.setForeground(java.awt.Color.darkGray);
        btnAbout.setText("?");
        btnAbout.setBorderPainted(false);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(7, 30, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("No es ninguna mentira, utilizamos resultados basados en investigaciones cientificas.");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 30, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRUEBALO YA!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnAction)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(btnAbout)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAbout)))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        String openingText = "Cargando...";
        JLabel openingLabel = new JLabel(openingText);
        openingLabel.setFont(new Font("Arial", Font.BOLD, 32));
        openingLabel.setHorizontalAlignment(SwingConstants.CENTER);
        openingLabel.setVerticalAlignment(SwingConstants.CENTER);
        
        //declaracion de los JPanel
        JPanel panelOpening = new JPanel(new BorderLayout());
        JPanel panelLoading = new JPanel();
        JPanel panel = new JPanel();
        
        panelOpening.setPreferredSize(new Dimension(550, 600));
        panelOpening.setMinimumSize(new Dimension(550, 600));
        panelOpening.setMaximumSize(new Dimension(550, Short.MAX_VALUE));
        
        panelOpening.add(openingLabel, BorderLayout.CENTER);
        
        JDialog dialogOpening = new JDialog();
        JDialog dialog = new JDialog();
        
        dialogOpening.setModal(false);
        dialogOpening.setTitle("Tu animal interior");
        dialogOpening.getContentPane().add(panelOpening);
        dialogOpening.pack();
        dialogOpening.setLocationRelativeTo(null);
        dialogOpening.setVisible(true);
        
        Timer cierreAutomatico = new Timer(500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dialogOpening.dispose();
            }
        });
        cierreAutomatico.setRepeats(false); // Solo una vez
        cierreAutomatico.start();
        
        try {
            //buscar siluetas de animales y pedir a la IA una transicion con gif
            String loadingText = "Analizando...";
            JLabel loadingTextLabel = new JLabel(loadingText);
            URL gifURL = new URL("https://juanxxiiizoo.infinityfreeapp.com/img/animalees.gif");
            ImageIcon originalGif = new ImageIcon(gifURL);
            JLabel loadingGifLabel = new JLabel(originalGif);
            panelLoading.setLayout(new BoxLayout(panelLoading, BoxLayout.Y_AXIS));  
            loadingTextLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
            loadingGifLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
            
            //estilo para los labels
            loadingTextLabel.setFont(new Font("Arial", Font.BOLD, 22));
            loadingTextLabel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 15));
            
            //preparar ventana de carga
            panelLoading.setPreferredSize(new Dimension(550, 600));
            panelLoading.setMinimumSize(new Dimension(550, 600));
            panelLoading.setMaximumSize(new Dimension(550, Short.MAX_VALUE));
            
            panelLoading.add(loadingTextLabel);
            panelLoading.add(loadingGifLabel);
            dialog.setModal(true);
            dialog.setTitle("Tu animal interior");
            dialog.getContentPane().add(panelLoading);
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            
        } catch (MalformedURLException ex) {
            Logger.getLogger(MiniZooMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
            Connection con = ConectionDB.connect();
            ArrayList<Integer> species = new ArrayList();
            if(con!=null){
                try{
                    String sql = "SELECT id FROM especies";
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery(sql);
                    while(rs.next()){
                        int id = rs.getInt("id");
                        species.add(id);
                    }
                    rs.close();
                    stmt.close();                    
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(rootPane,"Ha ocurrido un error en la primera consulta","Error al leer en la base de datos",JOptionPane.ERROR_MESSAGE);
                }
                if(species.size() > 0){
                    int length = species.size();
                    int index = (int)Math.floor(Math.random()*length);
                    int winnerID = species.get(index);
                    try{
                        String sql = "SELECT name,img FROM especies WHERE id = ?";
                        PreparedStatement stmt = con.prepareStatement(sql);
                        stmt.setInt(1, winnerID);
                        ResultSet rs = stmt.executeQuery();
                        
                        String specieName ="";
                        String imgURLString = "";
                        
                        if(rs.next()){
                            specieName = rs.getString("name");
                            imgURLString = "https://juanxxiiizoo.infinityfreeapp.com/"+rs.getString("img");
                        }
                        String qr = "https://juanxxiiizoo.infinityfreeapp.com/img/qr_"+winnerID+".png";
                        URL qrURL = new URL(qr);
                        stmt.close();
                        rs.close();
                        
                        //corrreccion de imagenes con espacio en el nombre
                        String fixedImgUrl = imgURLString.replace(" ", "%20");
                        URL imgURL = new URL(fixedImgUrl);
                        
                        String title = "Tu animal interior es:";
                        JLabel titleLabel = new JLabel(title);
                        JLabel nameLabel = new JLabel(specieName);
                        ImageIcon specieIcon = new ImageIcon(imgURL);
                        Image img = specieIcon.getImage();
                        if(specieIcon.getIconWidth() > specieIcon.getIconHeight()){
                            if(specieIcon.getIconWidth() > 350){
                                int newWidth = 350;
                                int newHeight = (int) ((double)specieIcon.getIconHeight()*newWidth)/specieIcon.getIconWidth();
                                if(newHeight > 240){
                                    newHeight = 240;
                                    newWidth = (specieIcon.getIconWidth() * newHeight) / specieIcon.getIconHeight();
                                }
                                img = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
                            }
                        }else if(specieIcon.getIconWidth() < specieIcon.getIconHeight()){
                            if(specieIcon.getIconHeight() > 240){
                                int newHeight = 240;
                                int newWidth = (specieIcon.getIconWidth() * newHeight) / specieIcon.getIconHeight();
                                img = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH);
                            }
                        }
                        ImageIcon specieImg = new ImageIcon(img);
                        JLabel imgLabel = new JLabel(specieImg);
                        String text = "Escanea el QR para obtener mas informacion";
                        JLabel textLabel = new JLabel(text);
                        ImageIcon specieQR = new ImageIcon(qrURL);
                        Image resizedQR = specieQR.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                        ImageIcon QR = new ImageIcon(resizedQR);
                        JLabel qrLabel = new JLabel(QR);
                        
                        titleLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                        nameLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                        imgLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                        textLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
                        qrLabel.setAlignmentX(Component.CENTER_ALIGNMENT);

                        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

                        //estilos para el resultado
                        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
                        titleLabel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 15));
                        
                        nameLabel.setFont(new Font("Arial", Font.BOLD, 26));
                        nameLabel.setBorder(BorderFactory.createEmptyBorder(15,0,15,0));
                        Color coffeBrown = new Color(101,67,33);
                        nameLabel.setForeground(coffeBrown);
                        
                        textLabel.setBorder(BorderFactory.createEmptyBorder(15,0,15,0));
                        textLabel.setFont(new Font("Arial", Font.PLAIN,20));
                        
                        panel.add(titleLabel);
                        panel.add(nameLabel);
                        panel.add(imgLabel);
                        panel.add(textLabel);
                        panel.add(qrLabel);
                        
                        JScrollPane scroll = new JScrollPane(panel);
                        scroll.setPreferredSize(new Dimension(550, 700));
                        scroll.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
                        scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
                        
                        new Thread(() -> {
                            try {
                                Thread.sleep(5000);
                                SwingUtilities.invokeLater(() -> {
                                    dialog.setVisible(false); 
                                    
                                    JOptionPane.showMessageDialog(null, scroll, "Resultado", JOptionPane.PLAIN_MESSAGE);
                                });
                            } catch (InterruptedException e) {
                                e.printStackTrace();
                            }
                        }).start();
                        
                        dialog.setVisible(true);
                        
                        
                        con.close();
                        
                        
                    }catch(SQLException e){
                        JOptionPane.showMessageDialog(rootPane,"Ha ocurrido un error en la segunda consulta","Error al leer en la base de datos",JOptionPane.ERROR_MESSAGE);
                    } catch (MalformedURLException ex) {
                        Logger.getLogger(MiniZooMainMenu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
    }//GEN-LAST:event_btnActionActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        String message = "Hola, somos estudiantes de segundo año de la carrera "
                + "Analisis de\nSistemas Informaticos de la UNAE, y este programa\n"
                + "es parte de nuestro proyecto interdiciplinario denominado \n"
                + "Mini-Zoo. El proyecto consisite en el desarrollo de un sitio web \n"
                + "para el Mini-Zoo Juan XXIII, el cual cuenta con una base de datos de \n"
                + "todas las especies que se encuentran en dicho zoo.\n"
                + "Aprovechando estos datos, decidimos crear este programa utilizando java.\n"
                + "Espero que te haya gustado :D";
        JOptionPane.showMessageDialog(null, message,"Sobre el programa",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MiniZooMainMenu menu = new MiniZooMainMenu();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
