/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mini.zoo;


import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
/**
 *
 * @author mierd
 */
public class MiniZooMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MiniZooMainMenu
     */
    public MiniZooMainMenu() {
        initComponents();
        Image image = new ImageIcon(getClass().getResource("/images/logoJXIII.png")).getImage();

        // Establecer el icono
        setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAction = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Que animal eres?");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(99, 34, 0));
        jLabel1.setText("¿Que animal eres?");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 30, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Este programa te dira el animal que serias si volvieras a nacer.");

        btnAction.setBackground(new java.awt.Color(23, 142, 24));
        btnAction.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAction.setForeground(java.awt.Color.white);
        btnAction.setText("Quiero saber!");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        btnAbout.setBackground(java.awt.Color.lightGray);
        btnAbout.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        btnAbout.setForeground(java.awt.Color.darkGray);
        btnAbout.setText("?");
        btnAbout.setBorderPainted(false);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(7, 30, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("No es ninguna mentira, utilizamos resultados basados en investigaciones cientificas.");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 30, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRUEBALO YA!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnAction)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(btnAbout)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAbout)))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        LoadingScreen loading = new LoadingScreen();
        
        new Thread(() -> {
            try {
                String[] data = Species.getRandomSpecie();
                Thread.sleep(3000);
                SwingUtilities.invokeLater(() -> {
                    JOptionPane.showMessageDialog(null, new ResultScreen(data), "Resultado", JOptionPane.PLAIN_MESSAGE);
                    loading.setVisible(false);             
                });
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }).start();
        
        loading.setVisible(true);           
    }//GEN-LAST:event_btnActionActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        String message = "<html><body style=\"width=250px\"><p>Hola, somos estudiantes de segundo año de la carrera "
                + "Analisis de Sistemas Informaticos de la <strong>UNAE</strong>, y este programa "
                + "es parte de nuestro proyecto interdiciplinario denominado "
                + "<strong>Mini-Zoo</strong>. El proyecto consisite en el desarrollo de un sitio web "
                + "para el Mini-Zoo Juan XXIII, el cual cuenta con una base de datos de "
                + "todas las especies que se encuentran en dicho zoo."
                + "Aprovechando estos datos, decidimos crear este programa utilizando java."
                + " Espero que te haya gustado :D</p>"
                + "<p><strong>Escanea el QR para acceder al codigo fuente de este programa:</strong></p></body></html>";
        String qr = "https://api.qrserver.com/v1/create-qr-code/?size=600x600&data=https://github.com/MiguelBenitez5/minizooJavaProyect/tree/master";
        URL qrURL = null;
        try {
            qrURL = new URL(qr);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MiniZooMainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon originalQR = new ImageIcon(qrURL);
        Image resizedQR = originalQR.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        ImageIcon QR = new ImageIcon(resizedQR);
        
        JLabel msgLabel = new JLabel(message);
        msgLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        msgLabel.setFont(new Font("Arial",Font.LAYOUT_LEFT_TO_RIGHT, 16));
        JLabel qrLabel = new JLabel(QR);
        qrLabel.setBorder(BorderFactory.createEmptyBorder(10,0,0,0));
        qrLabel.setAlignmentX(Component.CENTER_ALIGNMENT);
        
        JPanel panel = new JPanel();
        panel.setPreferredSize(new Dimension(500,370));
        panel.setLayout(new BoxLayout(panel,BoxLayout.Y_AXIS));
        panel.add(msgLabel);
        panel.add(qrLabel);
        
        JOptionPane.showMessageDialog(null, panel,"Sobre el programa",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniZooMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MiniZooMainMenu menu = new MiniZooMainMenu();
                menu.setLocationRelativeTo(null);
                menu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
